"""Note: the figure numbers used here are based on the preprint stage
https://doi.org/10.1101/2022.03.04.22271870
"""
from pathlib import Path

import pandas as pd

inclusion_expr = "failed_qc == 0 and excluded == 0"
samplesheet = pd.read_csv("../samples.paper.csv").query(inclusion_expr)
TECHS = ["illumina", "nanopore"]
DST_RESULTS = Path("../../analysis/resistance_prediction/results")
QC_RESULTS = Path("../../data/QC")
VARIANT_RESULTS = Path("../../analysis/baseline_variants/")
PHENOTYPES = Path("../phenotypes.csv")
FIGURES = Path("figures")
TABLES = Path("tables")
FIGURE_EXTS = [".png", ".svg"]
TABLE_EXTS = [".csv", ".tex"]
LOGDIR = Path("logs/rules")
ENVSDIR = Path("envs")
SCRIPTSDIR = Path("scripts")
ILLUMINA_DIST_THRESHOLDS = (5, 12)
NANOPORE_DIST_THRESHOLDS = (6, 12)
MIXED_DIST_THRESHOLDS = (6, 12)
DPI = 300
GB = 1_024

dst_concordance_files = set()
for site, sample in zip(samplesheet["site"], samplesheet["sample"]):
    for tech in TECHS:
        dst_concordance_files.add(
            str(DST_RESULTS / f"concordance/mykrobe/{tech}/{site}/{sample}.mykrobe.csv")
        )

required_files = set()

for ext in FIGURE_EXTS:
    required_files.add(FIGURES / f"figure_1{ext}")
    required_files.add(FIGURES / f"figure_3{ext}")
    required_files.add(FIGURES / f"figure_4{ext}")
    required_files.add(FIGURES / f"figure_5{ext}")
    required_files.add(FIGURES / f"figure_6{ext}")
    required_files.add(FIGURES / f"figure_S2{ext}")

for ext in TABLE_EXTS:
    required_files.add(TABLES / f"table_1{ext}")


rule all:
    input:
        required_files,


# ===============================
# FIGURES
# ===============================
rule figure_1:
    """Phenotype availability"""
    input:
        phenosheet=PHENOTYPES,
        concordance=dst_concordance_files,
    output:
        multiext(str(FIGURES / "figure_1"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_1.log",
    conda:
        str(ENVSDIR / "figure_1.yaml")
    params:
        style="ggplot",
        figsize=(10, 10),
        dpi=DPI,
        xticks=[],
        exclude=("pyrazinamide", "moxifloxacin"),
    script:
        str(SCRIPTSDIR / "figure_1.py")


rule figure_3:
    """Close dotplot"""
    input:
        compass_matrix=VARIANT_RESULTS / "distance/compass.matrix.csv",
        bcftools_matrix=VARIANT_RESULTS / "distance/bcftools.matrix.csv",
    output:
        multiext(str(FIGURES / "figure_3"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_3.log",
    conda:
        str(ENVSDIR / "figure_3.yaml")
    params:
        style="ggplot",
        figsize=(10, 10),
        dpi=DPI,
        marker_size=75,
        illumina_thresholds=ILLUMINA_DIST_THRESHOLDS,
        nanopore_thresholds=NANOPORE_DIST_THRESHOLDS,
        close_threshold=20,
        xaxis_label="COMPASS SNP distance",
        yaxis_label="BCFtools SNP distance",
        false_marker="s",
        font_size=14,
    script:
        str(SCRIPTSDIR / "figure_3.py")


rule figure_4:
    """Transmission clusters"""
    input:
        compass_matrix=VARIANT_RESULTS / "distance/compass.matrix.csv",
        bcftools_matrix=VARIANT_RESULTS / "distance/bcftools.matrix.csv",
    output:
        multiext(str(FIGURES / "figure_4"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_4.log",
    conda:
        str(ENVSDIR / "figure_4.yaml")
    params:
        style="default",
        figsize=(13, 13),
        dpi=DPI,
        illumina_thresholds=ILLUMINA_DIST_THRESHOLDS,
        nanopore_thresholds=NANOPORE_DIST_THRESHOLDS,
    script:
        str(SCRIPTSDIR / "figure_4.py")


rule figure_5:
    """Mixed simulations"""
    input:
        compass_matrix=VARIANT_RESULTS / "distance/compass.matrix.csv",
        bcftools_matrix=VARIANT_RESULTS / "distance/bcftools.matrix.csv",
        mixed_matrix=VARIANT_RESULTS / "distance/mixed.matrix.csv",
    output:
        multiext(str(FIGURES / "figure_5"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_5.log",
    conda:
        str(ENVSDIR / "figure_5.yaml")
    resources:
        mem_mb=int(2 * GB),
    params:
        style="ggplot",
        figsize=(10, 10),
        dpi=DPI,
        seed=1988,
        thresholds={
            ILLUMINA_DIST_THRESHOLDS[i]: {
                "ont": NANOPORE_DIST_THRESHOLDS[i],
                "mixed": MIXED_DIST_THRESHOLDS[i],
            }
            for i in range(len(ILLUMINA_DIST_THRESHOLDS))
        },
        ratios=[0.01, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9],
        num_simulations=1000,
        legend_loc="lower left",
        nrows=2,
        ncols=1,
        sharex=True,
        sharey=False,
        xaxis_label="Nanopore:Illumina ratio",
    script:
        str(SCRIPTSDIR / "figure_5.py")


rule figure_6:
    """Phenotype DST concordance bar plot"""
    input:
        phenosheet=PHENOTYPES,
        concordance=dst_concordance_files,
        coverage=QC_RESULTS / "report/coverage.csv",
    output:
        multiext(str(FIGURES / "figure_6"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_6.log",
    conda:
        str(ENVSDIR / "figure_6.yaml")
    params:
        style="ggplot",
        figsize=(13, 8),
        dpi=DPI,
        conf_interval=0.95,
        minor_is_susceptible=False,
        ignore_drugs={"pyrazinamide", "moxifloxacin"},
    script:
        str(SCRIPTSDIR / "figure_6.py")


rule figure_S2:
    """Full dotplot"""
    input:
        compass_matrix=VARIANT_RESULTS / "distance/compass.matrix.csv",
        bcftools_matrix=VARIANT_RESULTS / "distance/bcftools.matrix.csv",
    output:
        multiext(str(FIGURES / "figure_S2"), *FIGURE_EXTS),
    log:
        LOGDIR / "figure_S2.log",
    conda:
        str(ENVSDIR / "figure_S2.yaml")
    params:
        style="ggplot",
        figsize=(10, 10),
        dpi=DPI,
        xaxis_label="COMPASS SNP distance",
        yaxis_label="BCFtools SNP distance",
        font_size=14,
        alpha=0.25,
        linewidth=0.1,
        marker_size=20,
    script:
        str(SCRIPTSDIR / "figure_S2.py")


# ===============================
# TABLES
# ===============================
rule table_1:
    """Comparison of Mykrobe-derived Nanopore drug resistance predictions with 
    Illumina predictions
    """
    input:
        concordance=dst_concordance_files,
    output:
        csv=TABLES / "table_1.csv",
        latex=TABLES / "table_1.tex",
    log:
        LOGDIR / "table_1.log",
    conda:
        str(ENVSDIR / "table_1.yaml")
    params:
        conf_interval=0.95,
    script:
        str(SCRIPTSDIR / "table_1.py")
